name: "Newt Add-on"
version: "1.4.4"
slug: "newt"
description: "Runs Newt inside Home Assistant OS"
icon: "icon.png"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: system
boot: auto
host_network: true
privileged:
  # - SYS_ADMIN
  - NET_ADMIN
  - NET_RAW
  - DAC_READ_SEARCH
options:
  PANGOLIN_ENDPOINT: "https://example.com"
  NEWT_ID: "your_newt_id"
  NEWT_SECRET: "your_newt_secret"
schema:
  PANGOLIN_ENDPOINT: "str"
  NEWT_ID: "str"
  NEWT_SECRET: "str"
# Ensure that environment variables are set correctly
map:
  - config:rw
hassio_api: false
homeassistant_api: false
auth_api: false
# hassio_role: "admin"
# Reference the changelog
changelog: "https://raw.githubusercontent.com/sam-leenderts/home-assistant-newt-addon/main/CHANGELOG.md"
